# Generated by Django 2.0 on 2018-04-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piratapp', '0002_auto_20180420_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesouro',
            name='img_tesouro',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
