# Generated by Django 2.0 on 2018-04-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piratapp', '0003_auto_20180420_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesouro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
